//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_TemporyExclusif {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_TemporyExclusif() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources.TemporyExclusif", typeof(Resources_TemporyExclusif).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SERA SUPPRIMER A LA FIN DES OPERATIONS.
        /// </summary>
        public static string A_00EBENEZER_DONT_WRITE_HERE_ {
            get {
                return ResourceManager.GetString("A_00EBENEZER_DONT_WRITE_HERE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3CardController1_ {
            get {
                return ResourceManager.GetString("z3CardController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3CardController2_ {
            get {
                return ResourceManager.GetString("z3CardController2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController1_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController10_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController11_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController12_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController13_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController14_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController2_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController3_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController4_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController5_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController6_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController6_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController7_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController7_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController8_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController8_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ClientAgentController9_ {
            get {
                return ResourceManager.GetString("z3ClientAgentController9_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ManageController1_ {
            get {
                return ResourceManager.GetString("z3ManageController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ManageController2_ {
            get {
                return ResourceManager.GetString("z3ManageController2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ManageController3_ {
            get {
                return ResourceManager.GetString("z3ManageController3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ManageController4_ {
            get {
                return ResourceManager.GetString("z3ManageController4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ManageController5_ {
            get {
                return ResourceManager.GetString("z3ManageController5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ManageController6_ {
            get {
                return ResourceManager.GetString("z3ManageController6_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ManageController7_ {
            get {
                return ResourceManager.GetString("z3ManageController7_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3ManageController8_ {
            get {
                return ResourceManager.GetString("z3ManageController8_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3OnBehalfClientCommController1_ {
            get {
                return ResourceManager.GetString("z3OnBehalfClientCommController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController1_ {
            get {
                return ResourceManager.GetString("z3PKPCController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController10_ {
            get {
                return ResourceManager.GetString("z3PKPCController10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController11_ {
            get {
                return ResourceManager.GetString("z3PKPCController11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController12_ {
            get {
                return ResourceManager.GetString("z3PKPCController12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController13_ {
            get {
                return ResourceManager.GetString("z3PKPCController13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController14_ {
            get {
                return ResourceManager.GetString("z3PKPCController14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController15_ {
            get {
                return ResourceManager.GetString("z3PKPCController15_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController16_ {
            get {
                return ResourceManager.GetString("z3PKPCController16_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController17_ {
            get {
                return ResourceManager.GetString("z3PKPCController17_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController18_ {
            get {
                return ResourceManager.GetString("z3PKPCController18_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController19_ {
            get {
                return ResourceManager.GetString("z3PKPCController19_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController2_ {
            get {
                return ResourceManager.GetString("z3PKPCController2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController3_ {
            get {
                return ResourceManager.GetString("z3PKPCController3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController4_ {
            get {
                return ResourceManager.GetString("z3PKPCController4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController5_ {
            get {
                return ResourceManager.GetString("z3PKPCController5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController6_ {
            get {
                return ResourceManager.GetString("z3PKPCController6_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController7_ {
            get {
                return ResourceManager.GetString("z3PKPCController7_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController8_ {
            get {
                return ResourceManager.GetString("z3PKPCController8_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPCController9_ {
            get {
                return ResourceManager.GetString("z3PKPCController9_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController1_ {
            get {
                return ResourceManager.GetString("z3PKPController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController10_ {
            get {
                return ResourceManager.GetString("z3PKPController10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController11_ {
            get {
                return ResourceManager.GetString("z3PKPController11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController12_ {
            get {
                return ResourceManager.GetString("z3PKPController12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController13_ {
            get {
                return ResourceManager.GetString("z3PKPController13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController14_ {
            get {
                return ResourceManager.GetString("z3PKPController14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController15_ {
            get {
                return ResourceManager.GetString("z3PKPController15_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController16_ {
            get {
                return ResourceManager.GetString("z3PKPController16_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController17_ {
            get {
                return ResourceManager.GetString("z3PKPController17_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController18_ {
            get {
                return ResourceManager.GetString("z3PKPController18_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController2_ {
            get {
                return ResourceManager.GetString("z3PKPController2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController3_ {
            get {
                return ResourceManager.GetString("z3PKPController3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController4_ {
            get {
                return ResourceManager.GetString("z3PKPController4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController5_ {
            get {
                return ResourceManager.GetString("z3PKPController5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController6_ {
            get {
                return ResourceManager.GetString("z3PKPController6_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController7_ {
            get {
                return ResourceManager.GetString("z3PKPController7_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController8_ {
            get {
                return ResourceManager.GetString("z3PKPController8_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPController9_ {
            get {
                return ResourceManager.GetString("z3PKPController9_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPEController1_ {
            get {
                return ResourceManager.GetString("z3PKPEController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPEController2_ {
            get {
                return ResourceManager.GetString("z3PKPEController2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPEController3_ {
            get {
                return ResourceManager.GetString("z3PKPEController3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPEController4_ {
            get {
                return ResourceManager.GetString("z3PKPEController4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPEController5_ {
            get {
                return ResourceManager.GetString("z3PKPEController5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController1_ {
            get {
                return ResourceManager.GetString("z3PKPMController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController10_ {
            get {
                return ResourceManager.GetString("z3PKPMController10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController11_ {
            get {
                return ResourceManager.GetString("z3PKPMController11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController12_ {
            get {
                return ResourceManager.GetString("z3PKPMController12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController13_ {
            get {
                return ResourceManager.GetString("z3PKPMController13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController14_ {
            get {
                return ResourceManager.GetString("z3PKPMController14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController15_ {
            get {
                return ResourceManager.GetString("z3PKPMController15_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController16_ {
            get {
                return ResourceManager.GetString("z3PKPMController16_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController17_ {
            get {
                return ResourceManager.GetString("z3PKPMController17_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController18_ {
            get {
                return ResourceManager.GetString("z3PKPMController18_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController19_ {
            get {
                return ResourceManager.GetString("z3PKPMController19_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController2_ {
            get {
                return ResourceManager.GetString("z3PKPMController2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController20_ {
            get {
                return ResourceManager.GetString("z3PKPMController20_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController21_ {
            get {
                return ResourceManager.GetString("z3PKPMController21_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController22_ {
            get {
                return ResourceManager.GetString("z3PKPMController22_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController3_ {
            get {
                return ResourceManager.GetString("z3PKPMController3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController4_ {
            get {
                return ResourceManager.GetString("z3PKPMController4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController5_ {
            get {
                return ResourceManager.GetString("z3PKPMController5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController6_ {
            get {
                return ResourceManager.GetString("z3PKPMController6_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController7_ {
            get {
                return ResourceManager.GetString("z3PKPMController7_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController8_ {
            get {
                return ResourceManager.GetString("z3PKPMController8_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPMController9_ {
            get {
                return ResourceManager.GetString("z3PKPMController9_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPOController1_ {
            get {
                return ResourceManager.GetString("z3PKPOController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPOController2_ {
            get {
                return ResourceManager.GetString("z3PKPOController2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPOController3_ {
            get {
                return ResourceManager.GetString("z3PKPOController3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPOController4_ {
            get {
                return ResourceManager.GetString("z3PKPOController4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3PKPOController5_ {
            get {
                return ResourceManager.GetString("z3PKPOController5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController1_ {
            get {
                return ResourceManager.GetString("z3TransactionController1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController10_ {
            get {
                return ResourceManager.GetString("z3TransactionController10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController11_ {
            get {
                return ResourceManager.GetString("z3TransactionController11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController12_ {
            get {
                return ResourceManager.GetString("z3TransactionController12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController2_ {
            get {
                return ResourceManager.GetString("z3TransactionController2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController3_ {
            get {
                return ResourceManager.GetString("z3TransactionController3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController4_ {
            get {
                return ResourceManager.GetString("z3TransactionController4_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController5_ {
            get {
                return ResourceManager.GetString("z3TransactionController5_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController6_ {
            get {
                return ResourceManager.GetString("z3TransactionController6_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController7_ {
            get {
                return ResourceManager.GetString("z3TransactionController7_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController8_ {
            get {
                return ResourceManager.GetString("z3TransactionController8_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string z3TransactionController9_ {
            get {
                return ResourceManager.GetString("z3TransactionController9_", resourceCulture);
            }
        }
    }
}
