//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataModel : DbContext
    {
        public DataModel()
            : base("name=DataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCARD> TCARD { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<TACCT> TACCT { get; set; }
        public virtual DbSet<TACCT_BUS_AGNT_CMSN> TACCT_BUS_AGNT_CMSN { get; set; }
        public virtual DbSet<TACCT_BUS_SRVC> TACCT_BUS_SRVC { get; set; }
        public virtual DbSet<TACCT_CRDT> TACCT_CRDT { get; set; }
        public virtual DbSet<TACCT_HIST> TACCT_HIST { get; set; }
        public virtual DbSet<TACCT_ID> TACCT_ID { get; set; }
        public virtual DbSet<TAGNT> TAGNT { get; set; }
        public virtual DbSet<TAGNT_CMSN> TAGNT_CMSN { get; set; }
        public virtual DbSet<TAGNT_PKP_CMSN> TAGNT_PKP_CMSN { get; set; }
        public virtual DbSet<TAGNT_SPNSRD> TAGNT_SPNSRD { get; set; }
        public virtual DbSet<TAGNT_TRANS_CMSN> TAGNT_TRANS_CMSN { get; set; }
        public virtual DbSet<TAGNT_TRANS_CMSN_TEMPO> TAGNT_TRANS_CMSN_TEMPO { get; set; }
        public virtual DbSet<TAGNT_TRSF> TAGNT_TRSF { get; set; }
        public virtual DbSet<TBIL_PYMT_TRANS> TBIL_PYMT_TRANS { get; set; }
        public virtual DbSet<TBNK_TRANS> TBNK_TRANS { get; set; }
        public virtual DbSet<TBP> TBP { get; set; }
        public virtual DbSet<TBP_CTRCT> TBP_CTRCT { get; set; }
        public virtual DbSet<TBPCS> TBPCS { get; set; }
        public virtual DbSet<TBUS> TBUS { get; set; }
        public virtual DbSet<TBUS_AGCY> TBUS_AGCY { get; set; }
        public virtual DbSet<TBUS_AGCY_SRVC> TBUS_AGCY_SRVC { get; set; }
        public virtual DbSet<TBUS_CMSN> TBUS_CMSN { get; set; }
        public virtual DbSet<TBUS_CMSN_TRANS> TBUS_CMSN_TRANS { get; set; }
        public virtual DbSet<TBUS_CTRY_FEE> TBUS_CTRY_FEE { get; set; }
        public virtual DbSet<TBUS_INTRN_TRSF_TRANS> TBUS_INTRN_TRSF_TRANS { get; set; }
        public virtual DbSet<TBUS_TY> TBUS_TY { get; set; }
        public virtual DbSet<TBUS_USR> TBUS_USR { get; set; }
        public virtual DbSet<TBUS_USR_EXCP_ROL> TBUS_USR_EXCP_ROL { get; set; }
        public virtual DbSet<TCAL_CTRY> TCAL_CTRY { get; set; }
        public virtual DbSet<TCARD_ID> TCARD_ID { get; set; }
        public virtual DbSet<TCITY> TCITY { get; set; }
        public virtual DbSet<TCLT_IN_BUS> TCLT_IN_BUS { get; set; }
        public virtual DbSet<TCNX_LOG> TCNX_LOG { get; set; }
        public virtual DbSet<TCRCY> TCRCY { get; set; }
        public virtual DbSet<TCRCY_XCHG_PRCNT> TCRCY_XCHG_PRCNT { get; set; }
        public virtual DbSet<TCRCY_XCHG_RT> TCRCY_XCHG_RT { get; set; }
        public virtual DbSet<TCTRY> TCTRY { get; set; }
        public virtual DbSet<TCTRY_CRCY> TCTRY_CRCY { get; set; }
        public virtual DbSet<TEXCEPT_TRANS> TEXCEPT_TRANS { get; set; }
        public virtual DbSet<TEXRL_TRANS> TEXRL_TRANS { get; set; }
        public virtual DbSet<TFI> TFI { get; set; }
        public virtual DbSet<TFI_CTRY> TFI_CTRY { get; set; }
        public virtual DbSet<TFI_EXRL_ACCT> TFI_EXRL_ACCT { get; set; }
        public virtual DbSet<TFI_EXRL_ACCT_DESC> TFI_EXRL_ACCT_DESC { get; set; }
        public virtual DbSet<TFI_TY> TFI_TY { get; set; }
        public virtual DbSet<TID_DOC> TID_DOC { get; set; }
        public virtual DbSet<TIP_ADDR> TIP_ADDR { get; set; }
        public virtual DbSet<TKTCT> TKTCT { get; set; }
        public virtual DbSet<TLANG> TLANG { get; set; }
        public virtual DbSet<TMNYT_AUTH_LMIT> TMNYT_AUTH_LMIT { get; set; }
        public virtual DbSet<TMNYT_RSN> TMNYT_RSN { get; set; }
        public virtual DbSet<TONBHLF_CLT_CMSN> TONBHLF_CLT_CMSN { get; set; }
        public virtual DbSet<TONBHLF_CLT_TRANS> TONBHLF_CLT_TRANS { get; set; }
        public virtual DbSet<TPKP_TRCK_CMSN_FEE> TPKP_TRCK_CMSN_FEE { get; set; }
        public virtual DbSet<TPROV> TPROV { get; set; }
        public virtual DbSet<TPYMT_PRTR> TPYMT_PRTR { get; set; }
        public virtual DbSet<TRCPT_EXRL_ACCT_FOR_BUS> TRCPT_EXRL_ACCT_FOR_BUS { get; set; }
        public virtual DbSet<TRCPT_USR_BUS> TRCPT_USR_BUS { get; set; }
        public virtual DbSet<TSCTY_QUES_LIST> TSCTY_QUES_LIST { get; set; }
        public virtual DbSet<TTAX> TTAX { get; set; }
        public virtual DbSet<TTAX_RT_CTRY> TTAX_RT_CTRY { get; set; }
        public virtual DbSet<TTRANS_FEE> TTRANS_FEE { get; set; }
        public virtual DbSet<TTRANS_ID_DOC> TTRANS_ID_DOC { get; set; }
        public virtual DbSet<TTRANS_SSN> TTRANS_SSN { get; set; }
        public virtual DbSet<TTRANS_START_XSSN_TEMPO> TTRANS_START_XSSN_TEMPO { get; set; }
        public virtual DbSet<TTRANS_TEMPO> TTRANS_TEMPO { get; set; }
        public virtual DbSet<TTRANS_TRSF_CRDT_DBT> TTRANS_TRSF_CRDT_DBT { get; set; }
        public virtual DbSet<TTRSF_FEE_SERV_CTRY> TTRSF_FEE_SERV_CTRY { get; set; }
        public virtual DbSet<TTRSF_SERV> TTRSF_SERV { get; set; }
        public virtual DbSet<TTRSF_SERV_CTRY> TTRSF_SERV_CTRY { get; set; }
        public virtual DbSet<TUSR> TUSR { get; set; }
        public virtual DbSet<TUSR_ID> TUSR_ID { get; set; }
        public virtual DbSet<TUSR_WHDRL_CRDT> TUSR_WHDRL_CRDT { get; set; }
        public virtual DbSet<ZTMNYT_FEE_EXPIRED> ZTMNYT_FEE_EXPIRED { get; set; }
    
        [DbFunction("DataModel", "GetTransactionDetails")]
        public virtual IQueryable<GetTransactionDetails_Result> GetTransactionDetails(Nullable<int> transqctionID)
        {
            var transqctionIDParameter = transqctionID.HasValue ?
                new ObjectParameter("TransqctionID", transqctionID) :
                new ObjectParameter("TransqctionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTransactionDetails_Result>("[DataModel].[GetTransactionDetails](@TransqctionID)", transqctionIDParameter);
        }
    
        [DbFunction("DataModel", "GetTransactionDetailsWithPin")]
        public virtual IQueryable<GetTransactionDetailsWithPin_Result> GetTransactionDetailsWithPin(Nullable<int> transqctionID, string pinID)
        {
            var transqctionIDParameter = transqctionID.HasValue ?
                new ObjectParameter("TransqctionID", transqctionID) :
                new ObjectParameter("TransqctionID", typeof(int));
    
            var pinIDParameter = pinID != null ?
                new ObjectParameter("pinID", pinID) :
                new ObjectParameter("pinID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTransactionDetailsWithPin_Result>("[DataModel].[GetTransactionDetailsWithPin](@TransqctionID, @pinID)", transqctionIDParameter, pinIDParameter);
        }
    
        public virtual int InsertTransaction(Nullable<int> fROM_TRSF_SERV_ID, Nullable<int> tO_TRSF_SERV_ID, string fROM_CTRY_CD, string tO_CTRY_CD, string fROM_CRCY_CD, string tO_CRCY_CD, Nullable<decimal> cRCY_XCHG_RT, Nullable<decimal> fROM_TRANS_AMT, Nullable<decimal> fROM_FEE_AMT, Nullable<decimal> fROM_TOT_AMT, Nullable<decimal> tO_TRANS_AMT, string tRANS_SCD, Nullable<System.DateTime> tRANS_CDT, Nullable<System.DateTime> tRANS_PAID_DPST_DT, Nullable<System.DateTime> tRANS_XDT, string fROM_USR_NBR, Nullable<int> rCPT_USR_BUS_ID, string tRANS_TRSF_CRDT_DBT_TCD, string tRANS_DESC)
        {
            var fROM_TRSF_SERV_IDParameter = fROM_TRSF_SERV_ID.HasValue ?
                new ObjectParameter("FROM_TRSF_SERV_ID", fROM_TRSF_SERV_ID) :
                new ObjectParameter("FROM_TRSF_SERV_ID", typeof(int));
    
            var tO_TRSF_SERV_IDParameter = tO_TRSF_SERV_ID.HasValue ?
                new ObjectParameter("TO_TRSF_SERV_ID", tO_TRSF_SERV_ID) :
                new ObjectParameter("TO_TRSF_SERV_ID", typeof(int));
    
            var fROM_CTRY_CDParameter = fROM_CTRY_CD != null ?
                new ObjectParameter("FROM_CTRY_CD", fROM_CTRY_CD) :
                new ObjectParameter("FROM_CTRY_CD", typeof(string));
    
            var tO_CTRY_CDParameter = tO_CTRY_CD != null ?
                new ObjectParameter("TO_CTRY_CD", tO_CTRY_CD) :
                new ObjectParameter("TO_CTRY_CD", typeof(string));
    
            var fROM_CRCY_CDParameter = fROM_CRCY_CD != null ?
                new ObjectParameter("FROM_CRCY_CD", fROM_CRCY_CD) :
                new ObjectParameter("FROM_CRCY_CD", typeof(string));
    
            var tO_CRCY_CDParameter = tO_CRCY_CD != null ?
                new ObjectParameter("TO_CRCY_CD", tO_CRCY_CD) :
                new ObjectParameter("TO_CRCY_CD", typeof(string));
    
            var cRCY_XCHG_RTParameter = cRCY_XCHG_RT.HasValue ?
                new ObjectParameter("CRCY_XCHG_RT", cRCY_XCHG_RT) :
                new ObjectParameter("CRCY_XCHG_RT", typeof(decimal));
    
            var fROM_TRANS_AMTParameter = fROM_TRANS_AMT.HasValue ?
                new ObjectParameter("FROM_TRANS_AMT", fROM_TRANS_AMT) :
                new ObjectParameter("FROM_TRANS_AMT", typeof(decimal));
    
            var fROM_FEE_AMTParameter = fROM_FEE_AMT.HasValue ?
                new ObjectParameter("FROM_FEE_AMT", fROM_FEE_AMT) :
                new ObjectParameter("FROM_FEE_AMT", typeof(decimal));
    
            var fROM_TOT_AMTParameter = fROM_TOT_AMT.HasValue ?
                new ObjectParameter("FROM_TOT_AMT", fROM_TOT_AMT) :
                new ObjectParameter("FROM_TOT_AMT", typeof(decimal));
    
            var tO_TRANS_AMTParameter = tO_TRANS_AMT.HasValue ?
                new ObjectParameter("TO_TRANS_AMT", tO_TRANS_AMT) :
                new ObjectParameter("TO_TRANS_AMT", typeof(decimal));
    
            var tRANS_SCDParameter = tRANS_SCD != null ?
                new ObjectParameter("TRANS_SCD", tRANS_SCD) :
                new ObjectParameter("TRANS_SCD", typeof(string));
    
            var tRANS_CDTParameter = tRANS_CDT.HasValue ?
                new ObjectParameter("TRANS_CDT", tRANS_CDT) :
                new ObjectParameter("TRANS_CDT", typeof(System.DateTime));
    
            var tRANS_PAID_DPST_DTParameter = tRANS_PAID_DPST_DT.HasValue ?
                new ObjectParameter("TRANS_PAID_DPST_DT", tRANS_PAID_DPST_DT) :
                new ObjectParameter("TRANS_PAID_DPST_DT", typeof(System.DateTime));
    
            var tRANS_XDTParameter = tRANS_XDT.HasValue ?
                new ObjectParameter("TRANS_XDT", tRANS_XDT) :
                new ObjectParameter("TRANS_XDT", typeof(System.DateTime));
    
            var fROM_USR_NBRParameter = fROM_USR_NBR != null ?
                new ObjectParameter("FROM_USR_NBR", fROM_USR_NBR) :
                new ObjectParameter("FROM_USR_NBR", typeof(string));
    
            var rCPT_USR_BUS_IDParameter = rCPT_USR_BUS_ID.HasValue ?
                new ObjectParameter("RCPT_USR_BUS_ID", rCPT_USR_BUS_ID) :
                new ObjectParameter("RCPT_USR_BUS_ID", typeof(int));
    
            var tRANS_TRSF_CRDT_DBT_TCDParameter = tRANS_TRSF_CRDT_DBT_TCD != null ?
                new ObjectParameter("TRANS_TRSF_CRDT_DBT_TCD", tRANS_TRSF_CRDT_DBT_TCD) :
                new ObjectParameter("TRANS_TRSF_CRDT_DBT_TCD", typeof(string));
    
            var tRANS_DESCParameter = tRANS_DESC != null ?
                new ObjectParameter("TRANS_DESC", tRANS_DESC) :
                new ObjectParameter("TRANS_DESC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTransaction", fROM_TRSF_SERV_IDParameter, tO_TRSF_SERV_IDParameter, fROM_CTRY_CDParameter, tO_CTRY_CDParameter, fROM_CRCY_CDParameter, tO_CRCY_CDParameter, cRCY_XCHG_RTParameter, fROM_TRANS_AMTParameter, fROM_FEE_AMTParameter, fROM_TOT_AMTParameter, tO_TRANS_AMTParameter, tRANS_SCDParameter, tRANS_CDTParameter, tRANS_PAID_DPST_DTParameter, tRANS_XDTParameter, fROM_USR_NBRParameter, rCPT_USR_BUS_IDParameter, tRANS_TRSF_CRDT_DBT_TCDParameter, tRANS_DESCParameter);
        }
    
        [DbFunction("DataModel", "RetraitDetails1")]
        public virtual IQueryable<RetraitDetails1_Result> RetraitDetails1(Nullable<decimal> montant, string phoneNumber)
        {
            var montantParameter = montant.HasValue ?
                new ObjectParameter("montant", montant) :
                new ObjectParameter("montant", typeof(decimal));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RetraitDetails1_Result>("[DataModel].[RetraitDetails1](@montant, @phoneNumber)", montantParameter, phoneNumberParameter);
        }
    
        [DbFunction("DataModel", "RetraitDetails2")]
        public virtual IQueryable<RetraitDetails2_Result> RetraitDetails2(Nullable<decimal> montant, string phoneNumber)
        {
            var montantParameter = montant.HasValue ?
                new ObjectParameter("montant", montant) :
                new ObjectParameter("montant", typeof(decimal));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RetraitDetails2_Result>("[DataModel].[RetraitDetails2](@montant, @phoneNumber)", montantParameter, phoneNumberParameter);
        }
    
        [DbFunction("DataModel", "LastInsertedTransID")]
        public virtual IQueryable<Nullable<int>> LastInsertedTransID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[DataModel].[LastInsertedTransID]()");
        }
    
        [DbFunction("DataModel", "DeposDetails")]
        public virtual IQueryable<DeposDetails_Result> DeposDetails(Nullable<decimal> montant, string phoneNumber)
        {
            var montantParameter = montant.HasValue ?
                new ObjectParameter("montant", montant) :
                new ObjectParameter("montant", typeof(decimal));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DeposDetails_Result>("[DataModel].[DeposDetails](@montant, @phoneNumber)", montantParameter, phoneNumberParameter);
        }
    
        [DbFunction("DataModel", "GetDeposDetails")]
        public virtual IQueryable<GetDeposDetails_Result> GetDeposDetails(Nullable<decimal> montant, string phoneNumber)
        {
            var montantParameter = montant.HasValue ?
                new ObjectParameter("montant", montant) :
                new ObjectParameter("montant", typeof(decimal));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDeposDetails_Result>("[DataModel].[GetDeposDetails](@montant, @phoneNumber)", montantParameter, phoneNumberParameter);
        }
    
        [DbFunction("DataModel", "GetTransqtionDetails")]
        public virtual IQueryable<GetTransqtionDetails_Result> GetTransqtionDetails(Nullable<int> transqctionID)
        {
            var transqctionIDParameter = transqctionID.HasValue ?
                new ObjectParameter("TransqctionID", transqctionID) :
                new ObjectParameter("TransqctionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTransqtionDetails_Result>("[DataModel].[GetTransqtionDetails](@TransqctionID)", transqctionIDParameter);
        }
    }
}
