//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACCT_BUS_AGNT_CMSN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TACCT_BUS_AGNT_CMSN()
        {
            this.TAGNT = new HashSet<TAGNT>();
        }
    
        public int ACCT_ID { get; set; }
        public string ACCT_TCD { get; set; }
        public string CRCY_CD { get; set; }
        public string ACCT_NBR { get; set; }
        public decimal ACCT_BAL { get; set; }
        public string ACCT_CLTR_INFO { get; set; }
        public string ACCT_SCD { get; set; }
        public string BUS_AGNT_TCD { get; set; }
        public string DPLY_ACCT_TO_SPNSR_IND { get; set; }
        public string SPNSR_CNTL_CMSN_ACCT_IND { get; set; }
    
        public virtual TACCT TACCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT> TAGNT { get; set; }
    }
}
