//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACCT_CRDT
    {
        public int ACCT_ID { get; set; }
        public decimal ACCT_CRDT_AMT { get; set; }
        public System.DateTime ACCT_CRDT_DT { get; set; }
        public string ACCT_CRDT_CHCK_IND { get; set; }
    
        public virtual TACCT TACCT { get; set; }
    }
}
