//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TACCT()
        {
            this.TACCT_HIST = new HashSet<TACCT_HIST>();
            this.TRCPT_USR_BUS = new HashSet<TRCPT_USR_BUS>();
            this.TBUS_USR = new HashSet<TBUS_USR>();
            this.TBUS_AGCY = new HashSet<TBUS_AGCY>();
            this.TBUS = new HashSet<TBUS>();
            this.TBPCS = new HashSet<TBPCS>();
            this.TCLT_IN_BUS = new HashSet<TCLT_IN_BUS>();
            this.TACCT_BUS_SRVC = new HashSet<TACCT_BUS_SRVC>();
        }
    
        public int ACCT_ID { get; set; }
        public string ACCT_TCD { get; set; }
        public string CRCY_CD { get; set; }
        public string ACCT_SCD { get; set; }
        public string ACCT_NBR { get; set; }
        public string ACCT_NAME { get; set; }
        public decimal ACCT_BAL { get; set; }
        public string ACCT_CLTR_INFO { get; set; }
        public System.DateTime ACCT_CDT { get; set; }
        public string USR_NBR { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        public virtual TCRCY TCRCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACCT_HIST> TACCT_HIST { get; set; }
        public virtual TACCT_CRDT TACCT_CRDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRCPT_USR_BUS> TRCPT_USR_BUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_USR> TBUS_USR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_AGCY> TBUS_AGCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS> TBUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBPCS> TBPCS { get; set; }
        public virtual TACCT_BUS_AGNT_CMSN TACCT_BUS_AGNT_CMSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCLT_IN_BUS> TCLT_IN_BUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACCT_BUS_SRVC> TACCT_BUS_SRVC { get; set; }
        public virtual TUSR TUSR { get; set; }
    }
}
