//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGNT_TRANS_CMSN
    {
        public int AGNT_ID { get; set; }
        public string AGNT_SPNSR_TCD { get; set; }
        public string TRANS_ID { get; set; }
        public decimal TRANS_CMSN_AMT { get; set; }
        public System.DateTime TRANS_CMSN_DT { get; set; }
        public string TRANS_CMSN_CRCY_CD { get; set; }
        public string TRANS_CMSN_DESC { get; set; }
        public string TRANS_SPNSRD_NBR { get; set; }
        public string TRANS_SPNSRD_NM { get; set; }
        public string TRANS_SPNSRD_TCD { get; set; }
        public string SRVC_TCD { get; set; }
    
        public virtual TAGNT TAGNT { get; set; }
    }
}
