//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBNK_TRANS
    {
        public int TRANS_ID { get; set; }
        public string FROM_TO_USR_CD { get; set; }
        public int EXRL_ACCT_ID { get; set; }
        public string TRANS_TRSF_CRDT_DBT_TCD { get; set; }
        public System.DateTime BNK_TRANS_DT { get; set; }
        public string EXRL_BNK_TRANS_ID { get; set; }
        public System.DateTime EXRL_BNK_TRANS_DT { get; set; }
        public string EXRL_BNK_TRANS_DESC { get; set; }
        public string EXRL_BNK_TRANS_RCEIPT_FILE_NM { get; set; }
    
        public virtual TFI_EXRL_ACCT TFI_EXRL_ACCT { get; set; }
        public virtual TTRANS_TRSF_CRDT_DBT TTRANS_TRSF_CRDT_DBT { get; set; }
    }
}
