//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS_TY
    {
        public string BUS_TCD { get; set; }
        public int BN { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        public virtual TBUS TBUS { get; set; }
    }
}
