//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBUS()
        {
            this.TAGNT = new HashSet<TAGNT>();
            this.TAGNT_CMSN = new HashSet<TAGNT_CMSN>();
            this.TBP_CTRCT = new HashSet<TBP_CTRCT>();
            this.TBPCS = new HashSet<TBPCS>();
            this.TBUS_CMSN = new HashSet<TBUS_CMSN>();
            this.TRCPT_USR_BUS = new HashSet<TRCPT_USR_BUS>();
            this.TFI_EXRL_ACCT = new HashSet<TFI_EXRL_ACCT>();
            this.TRCPT_EXRL_ACCT_FOR_BUS = new HashSet<TRCPT_EXRL_ACCT_FOR_BUS>();
            this.TBUS_AGCY = new HashSet<TBUS_AGCY>();
            this.TCLT_IN_BUS = new HashSet<TCLT_IN_BUS>();
            this.TBUS_TY = new HashSet<TBUS_TY>();
        }
    
        public int BN { get; set; }
        public int KTCT_ID { get; set; }
        public int ACCT_ID { get; set; }
        public string BUS_NM { get; set; }
        public string BUS_SHORT_NM { get; set; }
        public string BUS_AREA { get; set; }
        public Nullable<int> CARD_ID { get; set; }
        public string BUS_SCD { get; set; }
        public string DFLT_BUS_DSPL_IND { get; set; }
    
        public virtual TACCT TACCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT> TAGNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT_CMSN> TAGNT_CMSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBP_CTRCT> TBP_CTRCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBPCS> TBPCS { get; set; }
        public virtual TKTCT TKTCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_CMSN> TBUS_CMSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRCPT_USR_BUS> TRCPT_USR_BUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFI_EXRL_ACCT> TFI_EXRL_ACCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRCPT_EXRL_ACCT_FOR_BUS> TRCPT_EXRL_ACCT_FOR_BUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_AGCY> TBUS_AGCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCLT_IN_BUS> TCLT_IN_BUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_TY> TBUS_TY { get; set; }
        public virtual TCARD TCARD { get; set; }
    }
}
