//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS_CMSN_TRANS
    {
        public int BUS_CMSN_TRANS_ID { get; set; }
        public int TRANS_ID { get; set; }
        public decimal BUS_CMSN_AMT { get; set; }
        public string CRCY_CD { get; set; }
        public int BUS_USR_NBR { get; set; }
        public string TRANS_TRSF_CRDT_DBT_TCD { get; set; }
    
        public virtual TTRANS_TRSF_CRDT_DBT TTRANS_TRSF_CRDT_DBT { get; set; }
        public virtual TBUS_USR TBUS_USR { get; set; }
        public virtual TCRCY TCRCY { get; set; }
    }
}
