//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS_CTRY_FEE
    {
        public int BUS_FEE_ID { get; set; }
        public string CTRY_CD { get; set; }
        public string CRCY_CD { get; set; }
        public string SRVC_TCD { get; set; }
        public decimal FROM_AMT { get; set; }
        public decimal TO_AMT { get; set; }
        public decimal FIX_FEE_AMT { get; set; }
        public decimal PRCNT_FEE_RT { get; set; }
        public string BUS_FEE_TCD { get; set; }
        public System.DateTime BUS_FEE_DT { get; set; }
    
        public virtual TCTRY TCTRY { get; set; }
        public virtual TCRCY TCRCY { get; set; }
    }
}
