//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCLT_IN_BUS
    {
        public string USR_NBR { get; set; }
        public int CARD_ID { get; set; }
        public int ACCT_ID { get; set; }
        public int BN { get; set; }
        public int BUS_USR_NBR { get; set; }
        public string SEND_MNY_IND { get; set; }
        public string WDRW_MNY_IND { get; set; }
        public string WDRW_MNY_WTT_PIN_IND { get; set; }
        public string BNK_DPST_IND { get; set; }
        public string RST_PWD_IND { get; set; }
        public string RST_CARD_PIN_IND { get; set; }
        public string MNGE_AGNT_IND { get; set; }
        public System.DateTime CLT_IN_BUS_EDT { get; set; }
        public System.DateTime CLT_IN_BUS_XDT { get; set; }
        public string LGC_DEL_IND { get; set; }
        public string OTH1_IND { get; set; }
        public string OTH2_IND { get; set; }
        public string OTH3_IND { get; set; }
        public string OTH4_IND { get; set; }
        public string OTH5_IND { get; set; }
    
        public virtual TACCT TACCT { get; set; }
        public virtual TBUS TBUS { get; set; }
        public virtual TBUS_USR TBUS_USR { get; set; }
        public virtual TCARD TCARD { get; set; }
        public virtual TUSR TUSR { get; set; }
    }
}
