//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCRCY_XCHG_PRCNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCRCY_XCHG_PRCNT()
        {
            this.TTRANS_FEE = new HashSet<TTRANS_FEE>();
        }
    
        public int CRCY_XCHG_PRCNT_ID { get; set; }
        public decimal IVSTR_CRCY_XCHG_PRCNT_RT { get; set; }
        public decimal NIVSTR_CRCY_XCHG_PRCNT_RT { get; set; }
        public System.DateTime CRCY_XCHG_PRCNT_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_FEE> TTRANS_FEE { get; set; }
    }
}
