//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCRCY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCRCY()
        {
            this.TACCT = new HashSet<TACCT>();
            this.TAGNT_PKP_CMSN = new HashSet<TAGNT_PKP_CMSN>();
            this.TBUS_CMSN = new HashSet<TBUS_CMSN>();
            this.TBUS_CMSN_TRANS = new HashSet<TBUS_CMSN_TRANS>();
            this.TBUS_CTRY_FEE = new HashSet<TBUS_CTRY_FEE>();
            this.TCRCY_XCHG_RT = new HashSet<TCRCY_XCHG_RT>();
            this.TCRCY_XCHG_RT1 = new HashSet<TCRCY_XCHG_RT>();
            this.TTRANS_TRSF_CRDT_DBT = new HashSet<TTRANS_TRSF_CRDT_DBT>();
            this.TTRANS_TRSF_CRDT_DBT1 = new HashSet<TTRANS_TRSF_CRDT_DBT>();
            this.ZTMNYT_FEE_EXPIRED = new HashSet<ZTMNYT_FEE_EXPIRED>();
            this.TMNYT_AUTH_LMIT = new HashSet<TMNYT_AUTH_LMIT>();
            this.TFI_EXRL_ACCT = new HashSet<TFI_EXRL_ACCT>();
            this.TTRANS_FEE = new HashSet<TTRANS_FEE>();
            this.TTRANS_FEE1 = new HashSet<TTRANS_FEE>();
            this.TCTRY_CRCY = new HashSet<TCTRY_CRCY>();
            this.TONBHLF_CLT_CMSN = new HashSet<TONBHLF_CLT_CMSN>();
            this.TONBHLF_CLT_TRANS = new HashSet<TONBHLF_CLT_TRANS>();
        }
    
        public string CRCY_CD { get; set; }
        public string CRCY_FRA_NM { get; set; }
        public string CRCY_ENG_NM { get; set; }
        public string CRCY_SPA_NM { get; set; }
        public string CRCY_ARB_NM { get; set; }
        public string CRCY_POR_NM { get; set; }
        public string CRCY_ZHO_NM { get; set; }
        public string CRCY_RUS_NM { get; set; }
        public string CRCY_DEU_NM { get; set; }
        public string CRCY_ITA_NM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACCT> TACCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT_PKP_CMSN> TAGNT_PKP_CMSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_CMSN> TBUS_CMSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_CMSN_TRANS> TBUS_CMSN_TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_CTRY_FEE> TBUS_CTRY_FEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCRCY_XCHG_RT> TCRCY_XCHG_RT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCRCY_XCHG_RT> TCRCY_XCHG_RT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_TRSF_CRDT_DBT> TTRANS_TRSF_CRDT_DBT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_TRSF_CRDT_DBT> TTRANS_TRSF_CRDT_DBT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZTMNYT_FEE_EXPIRED> ZTMNYT_FEE_EXPIRED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMNYT_AUTH_LMIT> TMNYT_AUTH_LMIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFI_EXRL_ACCT> TFI_EXRL_ACCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_FEE> TTRANS_FEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_FEE> TTRANS_FEE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCTRY_CRCY> TCTRY_CRCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONBHLF_CLT_CMSN> TONBHLF_CLT_CMSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONBHLF_CLT_TRANS> TONBHLF_CLT_TRANS { get; set; }
    }
}
