//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXRL_TRANS
    {
        public int EXRL_TRANS_ID { get; set; }
        public string PKP_TRANS_ID { get; set; }
        public string PRTR_TRANS_ID { get; set; }
        public string PRTR_TRANS_RCD { get; set; }
        public string EXRL_TRANS_NSS_ID { get; set; }
        public string EXRL_TRANS_OTH_DTL_TXT { get; set; }
        public string PYMT_PRTR_ID { get; set; }
        public System.DateTime EXRL_TRANS_DT { get; set; }
    
        public virtual TPYMT_PRTR TPYMT_PRTR { get; set; }
    }
}
