//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFI_EXRL_ACCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TFI_EXRL_ACCT()
        {
            this.TBNK_TRANS = new HashSet<TBNK_TRANS>();
            this.TRCPT_EXRL_ACCT_FOR_BUS = new HashSet<TRCPT_EXRL_ACCT_FOR_BUS>();
        }
    
        public int EXRL_ACCT_ID { get; set; }
        public string EXRL_ACCT_NM { get; set; }
        public string EXRL_ACCT_NBR { get; set; }
        public string EXRL_ACCT_TCD { get; set; }
        public string EXRL_ACCT_PRT1_NBR { get; set; }
        public string EXRL_ACCT_PRT2_NBR { get; set; }
        public string EXRL_ACCT_PRT3_NBR { get; set; }
        public string EXRL_ACCT_PRT4_NBR { get; set; }
        public string EXRL_ACCT_PRT5_NBR { get; set; }
        public int EXRL_ACCT_PRT_NBR { get; set; }
        public string EXRL_ACCT_VLDT_IND { get; set; }
        public System.DateTime EXRL_ACCT_DT { get; set; }
        public int FI_CTRY_ID { get; set; }
        public string CRCY_CD { get; set; }
        public string EXRL_ACCT_USR_NBR { get; set; }
        public Nullable<int> EXRL_ACCT_BUS_NBR { get; set; }
        public string EXRL_ACCT_USR_BUS_TCD { get; set; }
        public string USR_NBR { get; set; }
        public string EXRL_ACCT_FOR_CURT_USR_IND { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBNK_TRANS> TBNK_TRANS { get; set; }
        public virtual TBUS TBUS { get; set; }
        public virtual TCRCY TCRCY { get; set; }
        public virtual TFI_CTRY TFI_CTRY { get; set; }
        public virtual TUSR TUSR { get; set; }
        public virtual TUSR TUSR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRCPT_EXRL_ACCT_FOR_BUS> TRCPT_EXRL_ACCT_FOR_BUS { get; set; }
    }
}
