//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFI_CTRY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TFI_CTRY()
        {
            this.TFI_EXRL_ACCT = new HashSet<TFI_EXRL_ACCT>();
        }
    
        public int FI_CTRY_ID { get; set; }
        public string FI_CTRY_FRA_NM { get; set; }
        public string FI_CTRY_ENG_NM { get; set; }
        public string FI_CTRY_SPA_NM { get; set; }
        public string FI_CTRY_ARB_NM { get; set; }
        public string FI_CTRY_POR_NM { get; set; }
        public string FI_CTRY_ZHO_NM { get; set; }
        public string FI_CTRY_RUS_NM { get; set; }
        public string FI_CTRY_DEU_NM { get; set; }
        public string FI_CTRY_ITA_NM { get; set; }
        public string FI_CTRY_CD { get; set; }
        public int FI_ID { get; set; }
        public int FI_TCD { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        public virtual TCTRY TCTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFI_EXRL_ACCT> TFI_EXRL_ACCT { get; set; }
        public virtual TFI_TY TFI_TY { get; set; }
    }
}
