//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMNYT_RSN
    {
        public int MNYT_RSN_ID { get; set; }
        public string FRA_MNYT_RSN_NM { get; set; }
        public string ENG_MNYT_RSN_NM { get; set; }
        public string SPA_MNYT_RSN_NM { get; set; }
        public string ARB_MNYT_RSN_NM { get; set; }
        public string POR_MNYT_RSN_NM { get; set; }
        public string ZHO_MNYT_RSN_NM { get; set; }
        public string RUS_MNYT_RSN_NM { get; set; }
        public string DEU_MNYT_RSN_NM { get; set; }
        public string ITA_MNYT_RSN_NM { get; set; }
        public string LGC_DEL_IND { get; set; }
    }
}
