//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONBHLF_CLT_CMSN
    {
        public int CMSN_ID { get; set; }
        public string USR_NBR { get; set; }
        public string CTRY_CD { get; set; }
        public string SRVC_TCD { get; set; }
        public string CRCY_CD { get; set; }
        public decimal FIX_CMSN_AMT { get; set; }
        public decimal PRCNT_CMSN_RT { get; set; }
        public string CMSN_TCD { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        public virtual TCRCY TCRCY { get; set; }
        public virtual TCTRY TCTRY { get; set; }
        public virtual TUSR TUSR { get; set; }
    }
}
