//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRCPT_USR_BUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRCPT_USR_BUS()
        {
            this.TRCPT_EXRL_ACCT_FOR_BUS = new HashSet<TRCPT_EXRL_ACCT_FOR_BUS>();
            this.TTRANS_TRSF_CRDT_DBT = new HashSet<TTRANS_TRSF_CRDT_DBT>();
        }
    
        public int RCPT_USR_BUS_ID { get; set; }
        public int ACCT_ID { get; set; }
        public string ACCT_NBR { get; set; }
        public string RCPT_USR_BUS1_UIN { get; set; }
        public string RCPT_USR_BUS2_UIN { get; set; }
        public string RCPT_USR_BUS3_UIN { get; set; }
        public string RCPT_USR_BUS_NM { get; set; }
        public string RCPT_TCD { get; set; }
        public string RCPT_USR_NBR { get; set; }
        public Nullable<int> RCPT_BUS_NBR { get; set; }
        public string RCPT_USR_BUS_TCD { get; set; }
        public System.DateTime RCPT_USR_BUS_EDT { get; set; }
        public string USR_NBR { get; set; }
        public string LGC_DEL_IND { get; set; }
        public string ACTVT_TCD { get; set; }
    
        public virtual TACCT TACCT { get; set; }
        public virtual TBUS TBUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRCPT_EXRL_ACCT_FOR_BUS> TRCPT_EXRL_ACCT_FOR_BUS { get; set; }
        public virtual TUSR TUSR { get; set; }
        public virtual TUSR TUSR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_TRSF_CRDT_DBT> TTRANS_TRSF_CRDT_DBT { get; set; }
    }
}
