//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTAX
    {
        public int CASH_TRANS_CNBR { get; set; }
        public string TRANS_SRVC_TCD { get; set; }
        public decimal TRANS_AMT { get; set; }
        public decimal TAX_AMT { get; set; }
        public System.DateTime TRANS_DTTM { get; set; }
    }
}
