//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTRANS_ID_DOC
    {
        public int TRANS_ID { get; set; }
        public int ID_DOC_ID { get; set; }
        public string ID_DOC_NBR { get; set; }
        public System.DateTime ID_DOC_XDT { get; set; }
        public int BUS_USR_NBR { get; set; }
        public string CLT_USR_NBR { get; set; }
        public System.DateTime CLT_ID_DOC_BRDAY { get; set; }
        public System.DateTime TRANS_ID_DOC_DT { get; set; }
    
        public virtual TBUS_USR TBUS_USR { get; set; }
        public virtual TID_DOC TID_DOC { get; set; }
        public virtual TTRANS_TRSF_CRDT_DBT TTRANS_TRSF_CRDT_DBT { get; set; }
        public virtual TUSR TUSR { get; set; }
    }
}
