//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTRANS_SSN
    {
        public long TRANS_SSN_ID { get; set; }
        public string TRANS_SSN_SECR_ID { get; set; }
        public decimal TRANS_SSN_AMT { get; set; }
        public string TRANS_SSN_AMT_TXT { get; set; }
        public string TRANS_SSN_CUST_AMT_IND { get; set; }
        public System.DateTime TRANS_SSN_EDTTM { get; set; }
        public System.DateTime TRANS_SSN_XDTTM { get; set; }
        public string TRANS_SSN_BPC_ID { get; set; }
        public int BPCS_NBR { get; set; }
        public string USR_NBR { get; set; }
        public string CLT_ACCT_NBR { get; set; }
        public string CLT_ACCT_NBR_NEED_IND { get; set; }
        public string BIL_NBR { get; set; }
        public string BIL_NBR_NEED_IND { get; set; }
    
        public virtual TBPCS TBPCS { get; set; }
        public virtual TUSR TUSR { get; set; }
    }
}
