//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSR_WHDRL_CRDT
    {
        public string USR_NBR { get; set; }
        public int USR_WHDRL_CRDT_NBR { get; set; }
    
        public virtual TUSR TUSR { get; set; }
    }
}
