//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPaykapTransaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUSR()
        {
            this.TACCT = new HashSet<TACCT>();
            this.TAGNT = new HashSet<TAGNT>();
            this.TBP_CTRCT = new HashSet<TBP_CTRCT>();
            this.TBUS_USR = new HashSet<TBUS_USR>();
            this.TCARD = new HashSet<TCARD>();
            this.TCRCY_XCHG_RT = new HashSet<TCRCY_XCHG_RT>();
            this.TEXCEPT_TRANS = new HashSet<TEXCEPT_TRANS>();
            this.TFI_EXRL_ACCT = new HashSet<TFI_EXRL_ACCT>();
            this.TFI_EXRL_ACCT1 = new HashSet<TFI_EXRL_ACCT>();
            this.TIP_ADDR = new HashSet<TIP_ADDR>();
            this.TONBHLF_CLT_CMSN = new HashSet<TONBHLF_CLT_CMSN>();
            this.TONBHLF_CLT_TRANS = new HashSet<TONBHLF_CLT_TRANS>();
            this.TRCPT_USR_BUS = new HashSet<TRCPT_USR_BUS>();
            this.TRCPT_USR_BUS1 = new HashSet<TRCPT_USR_BUS>();
            this.TTRANS_ID_DOC = new HashSet<TTRANS_ID_DOC>();
            this.TTRANS_SSN = new HashSet<TTRANS_SSN>();
            this.TTRANS_TRSF_CRDT_DBT = new HashSet<TTRANS_TRSF_CRDT_DBT>();
        }
    
        public string USR_NBR { get; set; }
        public string USR_TCD { get; set; }
        public string USR_SCD { get; set; }
        public string USR_FNM { get; set; }
        public string USR_LNM { get; set; }
        public string USR_GNDR { get; set; }
        public System.DateTime USR_BRDAY { get; set; }
        public string USR_PREF_LCD { get; set; }
        public int USR_KTCT_ID { get; set; }
        public string USR_99P_FRC_IND { get; set; }
        public string USR_VERIF_IND { get; set; }
        public System.DateTime USR_MBRSHP_EDT { get; set; }
        public string Id { get; set; }
        public string USR_DFLT_PWD_IND { get; set; }
        public string USR_DFLT_EMAIL_IND { get; set; }
        public string USR_EMAIL_VRFT_IND { get; set; }
        public System.DateTime USR_EMAIL_VRFT_DT { get; set; }
        public string ADDR_LN1_TXT { get; set; }
        public string ADDR_LN2_TXT { get; set; }
        public string PHN1_NBR { get; set; }
        public string PHN1_CTRY_CD { get; set; }
        public string PHN1_CTRY_CD_NBR { get; set; }
        public string PHN1_CTRY_CD_NBR_VLDT_IND { get; set; }
        public System.DateTime PHN1_CTRY_CD_NBR_LAST_VLDT_DT { get; set; }
        public string PHN1_CTRY_CD_NBR_LGC_DEL_IND { get; set; }
        public string PHN2_NBR { get; set; }
        public string PHN2_CTRY_CD { get; set; }
        public string PHN2_CTRY_CD_NBR { get; set; }
        public string PHN2_CTRY_CD_NBR_VLDT_IND { get; set; }
        public System.DateTime PHN2_CTRY_CD_NBR_LAST_VLDT_DT { get; set; }
        public string PHN2_CTRY_CD_NBR_LGC_DEL_IND { get; set; }
        public string PHN3_NBR { get; set; }
        public string PHN3_CTRY_CD { get; set; }
        public string PHN3_CTRY_CD_NBR { get; set; }
        public string PHN3_CTRY_CD_NBR_VLDT_IND { get; set; }
        public System.DateTime PHN3_CTRY_CD_NBR_LAST_VLDT_DT { get; set; }
        public string PHN3_CTRY_CD_NBR_LGC_DEL_IND { get; set; }
        public string EMAIL1_TXT { get; set; }
        public string EMAIL2_TXT { get; set; }
        public string CITY_NM { get; set; }
        public Nullable<int> CITY_CD { get; set; }
        public string CTRY_CD { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACCT> TACCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT> TAGNT { get; set; }
        public virtual TAGNT_SPNSRD TAGNT_SPNSRD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBP_CTRCT> TBP_CTRCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_USR> TBUS_USR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCARD> TCARD { get; set; }
        public virtual TCITY TCITY { get; set; }
        public virtual TCLT_IN_BUS TCLT_IN_BUS { get; set; }
        public virtual TCNX_LOG TCNX_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCRCY_XCHG_RT> TCRCY_XCHG_RT { get; set; }
        public virtual TCTRY TCTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEXCEPT_TRANS> TEXCEPT_TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFI_EXRL_ACCT> TFI_EXRL_ACCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFI_EXRL_ACCT> TFI_EXRL_ACCT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIP_ADDR> TIP_ADDR { get; set; }
        public virtual TKTCT TKTCT { get; set; }
        public virtual TLANG TLANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONBHLF_CLT_CMSN> TONBHLF_CLT_CMSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONBHLF_CLT_TRANS> TONBHLF_CLT_TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRCPT_USR_BUS> TRCPT_USR_BUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRCPT_USR_BUS> TRCPT_USR_BUS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_ID_DOC> TTRANS_ID_DOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_SSN> TTRANS_SSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_TRSF_CRDT_DBT> TTRANS_TRSF_CRDT_DBT { get; set; }
        public virtual TUSR_WHDRL_CRDT TUSR_WHDRL_CRDT { get; set; }
    }
}
