//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PaykapDataModel : DbContext
    {
        public PaykapDataModel()
            : base("name=PaykapDataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<TACCT> TACCT { get; set; }
        public virtual DbSet<TACCT_BUS_AGNT_CMSN> TACCT_BUS_AGNT_CMSN { get; set; }
        public virtual DbSet<TACCT_BUS_SRVC> TACCT_BUS_SRVC { get; set; }
        public virtual DbSet<TACCT_CRDT> TACCT_CRDT { get; set; }
        public virtual DbSet<TACCT_HIST> TACCT_HIST { get; set; }
        public virtual DbSet<TACCT_ID> TACCT_ID { get; set; }
        public virtual DbSet<TAGNT> TAGNT { get; set; }
        public virtual DbSet<TAGNT_CMSN> TAGNT_CMSN { get; set; }
        public virtual DbSet<TAGNT_PKP_CMSN> TAGNT_PKP_CMSN { get; set; }
        public virtual DbSet<TAGNT_SPNSRD> TAGNT_SPNSRD { get; set; }
        public virtual DbSet<TAGNT_TRANS_CMSN> TAGNT_TRANS_CMSN { get; set; }
        public virtual DbSet<TAGNT_TRANS_CMSN_TEMPO> TAGNT_TRANS_CMSN_TEMPO { get; set; }
        public virtual DbSet<TAGNT_TRSF> TAGNT_TRSF { get; set; }
        public virtual DbSet<TBIL_PYMT_TRANS> TBIL_PYMT_TRANS { get; set; }
        public virtual DbSet<TBNK_TRANS> TBNK_TRANS { get; set; }
        public virtual DbSet<TBP> TBP { get; set; }
        public virtual DbSet<TBP_CTRCT> TBP_CTRCT { get; set; }
        public virtual DbSet<TBPCS> TBPCS { get; set; }
        public virtual DbSet<TBUS> TBUS { get; set; }
        public virtual DbSet<TBUS_AGCY> TBUS_AGCY { get; set; }
        public virtual DbSet<TBUS_AGCY_SRVC> TBUS_AGCY_SRVC { get; set; }
        public virtual DbSet<TBUS_CMSN> TBUS_CMSN { get; set; }
        public virtual DbSet<TBUS_CMSN_TRANS> TBUS_CMSN_TRANS { get; set; }
        public virtual DbSet<TBUS_CTRY_FEE> TBUS_CTRY_FEE { get; set; }
        public virtual DbSet<TBUS_INTRN_TRSF_TRANS> TBUS_INTRN_TRSF_TRANS { get; set; }
        public virtual DbSet<TBUS_TY> TBUS_TY { get; set; }
        public virtual DbSet<TBUS_USR> TBUS_USR { get; set; }
        public virtual DbSet<TBUS_USR_EXCP_ROL> TBUS_USR_EXCP_ROL { get; set; }
        public virtual DbSet<TCAL_CTRY> TCAL_CTRY { get; set; }
        public virtual DbSet<TCARD> TCARD { get; set; }
        public virtual DbSet<TCARD_ID> TCARD_ID { get; set; }
        public virtual DbSet<TCITY> TCITY { get; set; }
        public virtual DbSet<TCLT_IN_BUS> TCLT_IN_BUS { get; set; }
        public virtual DbSet<TCNX_LOG> TCNX_LOG { get; set; }
        public virtual DbSet<TCRCY> TCRCY { get; set; }
        public virtual DbSet<TCRCY_XCHG_PRCNT> TCRCY_XCHG_PRCNT { get; set; }
        public virtual DbSet<TCRCY_XCHG_RT> TCRCY_XCHG_RT { get; set; }
        public virtual DbSet<TCTRY> TCTRY { get; set; }
        public virtual DbSet<TCTRY_CRCY> TCTRY_CRCY { get; set; }
        public virtual DbSet<TEXCEPT_TRANS> TEXCEPT_TRANS { get; set; }
        public virtual DbSet<TEXRL_TRANS> TEXRL_TRANS { get; set; }
        public virtual DbSet<TFI> TFI { get; set; }
        public virtual DbSet<TFI_CTRY> TFI_CTRY { get; set; }
        public virtual DbSet<TFI_EXRL_ACCT> TFI_EXRL_ACCT { get; set; }
        public virtual DbSet<TFI_EXRL_ACCT_DESC> TFI_EXRL_ACCT_DESC { get; set; }
        public virtual DbSet<TFI_TY> TFI_TY { get; set; }
        public virtual DbSet<TID_DOC> TID_DOC { get; set; }
        public virtual DbSet<TIP_ADDR> TIP_ADDR { get; set; }
        public virtual DbSet<TKTCT> TKTCT { get; set; }
        public virtual DbSet<TLANG> TLANG { get; set; }
        public virtual DbSet<TMNYT_AUTH_LMIT> TMNYT_AUTH_LMIT { get; set; }
        public virtual DbSet<TMNYT_RSN> TMNYT_RSN { get; set; }
        public virtual DbSet<TONBHLF_CLT_CMSN> TONBHLF_CLT_CMSN { get; set; }
        public virtual DbSet<TONBHLF_CLT_TRANS> TONBHLF_CLT_TRANS { get; set; }
        public virtual DbSet<TPKP_TRCK_CMSN_FEE> TPKP_TRCK_CMSN_FEE { get; set; }
        public virtual DbSet<TPROV> TPROV { get; set; }
        public virtual DbSet<TPYMT_PRTR> TPYMT_PRTR { get; set; }
        public virtual DbSet<TRCPT_EXRL_ACCT_FOR_BUS> TRCPT_EXRL_ACCT_FOR_BUS { get; set; }
        public virtual DbSet<TRCPT_USR_BUS> TRCPT_USR_BUS { get; set; }
        public virtual DbSet<TSCTY_QUES_LIST> TSCTY_QUES_LIST { get; set; }
        public virtual DbSet<TTAX> TTAX { get; set; }
        public virtual DbSet<TTAX_RT_CTRY> TTAX_RT_CTRY { get; set; }
        public virtual DbSet<TTRANS_FEE> TTRANS_FEE { get; set; }
        public virtual DbSet<TTRANS_ID_DOC> TTRANS_ID_DOC { get; set; }
        public virtual DbSet<TTRANS_SSN> TTRANS_SSN { get; set; }
        public virtual DbSet<TTRANS_START_XSSN_TEMPO> TTRANS_START_XSSN_TEMPO { get; set; }
        public virtual DbSet<TTRANS_TEMPO> TTRANS_TEMPO { get; set; }
        public virtual DbSet<TTRANS_TRSF_CRDT_DBT> TTRANS_TRSF_CRDT_DBT { get; set; }
        public virtual DbSet<TTRSF_FEE_SERV_CTRY> TTRSF_FEE_SERV_CTRY { get; set; }
        public virtual DbSet<TTRSF_SERV> TTRSF_SERV { get; set; }
        public virtual DbSet<TTRSF_SERV_CTRY> TTRSF_SERV_CTRY { get; set; }
        public virtual DbSet<TUSR> TUSR { get; set; }
        public virtual DbSet<TUSR_ID> TUSR_ID { get; set; }
        public virtual DbSet<TUSR_WHDRL_CRDT> TUSR_WHDRL_CRDT { get; set; }
        public virtual DbSet<ZTMNYT_FEE_EXPIRED> ZTMNYT_FEE_EXPIRED { get; set; }
    
        [DbFunction("PaykapDataModel", "GetTransactionDetails")]
        public virtual IQueryable<GetTransactionDetails_Result> GetTransactionDetails(Nullable<int> transqctionID)
        {
            var transqctionIDParameter = transqctionID.HasValue ?
                new ObjectParameter("TransqctionID", transqctionID) :
                new ObjectParameter("TransqctionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTransactionDetails_Result>("[PaykapDataModel].[GetTransactionDetails](@TransqctionID)", transqctionIDParameter);
        }
    
        [DbFunction("PaykapDataModel", "DeposDetails")]
        public virtual IQueryable<DeposDetails_Result> DeposDetails(Nullable<decimal> montant, string phoneNumber)
        {
            var montantParameter = montant.HasValue ?
                new ObjectParameter("montant", montant) :
                new ObjectParameter("montant", typeof(decimal));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DeposDetails_Result>("[PaykapDataModel].[DeposDetails](@montant, @phoneNumber)", montantParameter, phoneNumberParameter);
        }
    
        [DbFunction("PaykapDataModel", "GetDeposDetails")]
        public virtual IQueryable<GetDeposDetails_Result> GetDeposDetails(Nullable<decimal> montant, string phoneNumber)
        {
            var montantParameter = montant.HasValue ?
                new ObjectParameter("montant", montant) :
                new ObjectParameter("montant", typeof(decimal));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDeposDetails_Result>("[PaykapDataModel].[GetDeposDetails](@montant, @phoneNumber)", montantParameter, phoneNumberParameter);
        }
    
        [DbFunction("PaykapDataModel", "LastInsertedTransID")]
        public virtual IQueryable<Nullable<int>> LastInsertedTransID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[PaykapDataModel].[LastInsertedTransID]()");
        }
    
        [DbFunction("PaykapDataModel", "RetraitDetails2")]
        public virtual IQueryable<RetraitDetails2_Result> RetraitDetails2(Nullable<decimal> montant, string phoneNumber)
        {
            var montantParameter = montant.HasValue ?
                new ObjectParameter("montant", montant) :
                new ObjectParameter("montant", typeof(decimal));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RetraitDetails2_Result>("[PaykapDataModel].[RetraitDetails2](@montant, @phoneNumber)", montantParameter, phoneNumberParameter);
        }
    }
}
