//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACCT_BUS_SRVC
    {
        public int ACCT_ID { get; set; }
        public string ACCT_BUS_SRVC_CD { get; set; }
        public string ACCT_TCD { get; set; }
        public string CRCY_CD { get; set; }
        public string ACCT_NBR { get; set; }
        public decimal ACCT_BAL { get; set; }
        public string ACCT_CLTR_INFO { get; set; }
        public string ACCT_SCD { get; set; }
        public string ACCT_OTH1_IND { get; set; }
        public string ACCT_OTH2_IND { get; set; }
    
        public virtual TACCT TACCT { get; set; }
    }
}
