//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACCT_HIST
    {
        public int ACCT_HIST_ID { get; set; }
        public int ACCT_ID { get; set; }
        public string TRANS_TCD { get; set; }
        public string TRANS_PAY_SRC_CD { get; set; }
        public string TRANS_SRVC_TCD { get; set; }
        public decimal BAL_AFTR_TRANS { get; set; }
        public decimal TRANS_AMT { get; set; }
        public System.DateTime TRANS_DTTM { get; set; }
        public string TRANS_DESC { get; set; }
    
        public virtual TACCT TACCT { get; set; }
    }
}
