//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAGNT()
        {
            this.TAGNT_CMSN = new HashSet<TAGNT_CMSN>();
            this.TAGNT_TRANS_CMSN = new HashSet<TAGNT_TRANS_CMSN>();
            this.TAGNT_SPNSRD = new HashSet<TAGNT_SPNSRD>();
            this.TAGNT1 = new HashSet<TAGNT>();
            this.TAGNT_TRSF = new HashSet<TAGNT_TRSF>();
        }
    
        public int AGNT_ID { get; set; }
        public string AGNT_NM { get; set; }
        public string AGNT_EXP_IND { get; set; }
        public System.DateTime AGNT_EDT { get; set; }
        public System.DateTime AGNT_XDT { get; set; }
        public string AGNT_USR_NBR { get; set; }
        public Nullable<int> AGNT_BUS_NBR { get; set; }
        public string AGNT_BUS_USR_TCD { get; set; }
        public int AGNT_ACCT_ID { get; set; }
        public string AGNT_TKN_CD { get; set; }
        public Nullable<int> SPNSR_AGNT_ID { get; set; }
        public string SPNSR_AGNT_IND { get; set; }
    
        public virtual TACCT_BUS_AGNT_CMSN TACCT_BUS_AGNT_CMSN { get; set; }
        public virtual TUSR TUSR { get; set; }
        public virtual TBUS TBUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT_CMSN> TAGNT_CMSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT_TRANS_CMSN> TAGNT_TRANS_CMSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT_SPNSRD> TAGNT_SPNSRD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT> TAGNT1 { get; set; }
        public virtual TAGNT TAGNT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGNT_TRSF> TAGNT_TRSF { get; set; }
    }
}
