//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGNT_TRSF
    {
        public int AGNT_ID { get; set; }
        public int AGNT_TRSF_ID { get; set; }
        public decimal AGNT_TRSF_AMT { get; set; }
        public System.DateTime AGNT_TRSF_DT { get; set; }
        public string CRCY_CD { get; set; }
    
        public virtual TAGNT TAGNT { get; set; }
    }
}
