//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBP()
        {
            this.TBP_CTRCT = new HashSet<TBP_CTRCT>();
        }
    
        public int BP_ID { get; set; }
        public string BP_FRA_NM { get; set; }
        public string BP_ENG_NM { get; set; }
        public string BP_SPA_NM { get; set; }
        public string BP_ARB_NM { get; set; }
        public string BP_POR_NM { get; set; }
        public string BP_ZHO_NM { get; set; }
        public string BP_RUS_NM { get; set; }
        public string BP_DEU_NM { get; set; }
        public string BP_ITA_NM { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBP_CTRCT> TBP_CTRCT { get; set; }
    }
}
