//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBP_CTRCT
    {
        public string BP_CTRCT_NBR { get; set; }
        public int BN { get; set; }
        public int BP_ID { get; set; }
        public System.DateTime BP_CTRCT_EDT { get; set; }
        public System.DateTime BP_CTRCT_XDT { get; set; }
        public string BP_CTRCT_CRT_USR_NBR { get; set; }
    
        public virtual TBP TBP { get; set; }
        public virtual TBUS TBUS { get; set; }
        public virtual TUSR TUSR { get; set; }
    }
}
