//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPCS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBPCS()
        {
            this.TTRANS_SSN = new HashSet<TTRANS_SSN>();
        }
    
        public int BPCS_NBR { get; set; }
        public string BPCS_BUS_ID { get; set; }
        public string BPCS_BUS_NM { get; set; }
        public string BPCS_CLT_ACCT_DESC { get; set; }
        public string BPCS_URL_TXT { get; set; }
        public string BPCS_URL_NEED_IND { get; set; }
        public int ACCT_ID { get; set; }
        public string ACCT_CRCY_CD { get; set; }
        public int BN { get; set; }
    
        public virtual TACCT TACCT { get; set; }
        public virtual TBUS TBUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_SSN> TTRANS_SSN { get; set; }
    }
}
