//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS_USR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBUS_USR()
        {
            this.TBUS_CMSN_TRANS = new HashSet<TBUS_CMSN_TRANS>();
            this.TBUS_INTRN_TRSF_TRANS = new HashSet<TBUS_INTRN_TRSF_TRANS>();
            this.TBUS_INTRN_TRSF_TRANS1 = new HashSet<TBUS_INTRN_TRSF_TRANS>();
            this.TBUS_USR_EXCP_ROL = new HashSet<TBUS_USR_EXCP_ROL>();
            this.TTRANS_ID_DOC = new HashSet<TTRANS_ID_DOC>();
            this.TCLT_IN_BUS = new HashSet<TCLT_IN_BUS>();
        }
    
        public int BUS_USR_NBR { get; set; }
        public int BN { get; set; }
        public string BUS_AGCY_NBR { get; set; }
        public int BUS_ACCT_ID { get; set; }
        public System.DateTime BUS_USR_EDT { get; set; }
        public string BUS_USR_TCD { get; set; }
        public decimal BUS_AV_CAMT { get; set; }
        public string BUS_EMPE_USR_NBR { get; set; }
        public string BUS_USR_SCD { get; set; }
        public string BUS_EMPE_IS_PKP_CLT_IND { get; set; }
    
        public virtual TACCT TACCT { get; set; }
        public virtual TBUS_AGCY TBUS_AGCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_CMSN_TRANS> TBUS_CMSN_TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_INTRN_TRSF_TRANS> TBUS_INTRN_TRSF_TRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_INTRN_TRSF_TRANS> TBUS_INTRN_TRSF_TRANS1 { get; set; }
        public virtual TUSR TUSR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_USR_EXCP_ROL> TBUS_USR_EXCP_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_ID_DOC> TTRANS_ID_DOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCLT_IN_BUS> TCLT_IN_BUS { get; set; }
    }
}
