//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS_INTRN_TRSF_TRANS
    {
        public int TRANS_ID { get; set; }
        public int FROM_BUS_USR_NBR { get; set; }
        public string FROM_BUS_USR_NM { get; set; }
        public int TO_BUS_USR_NBR { get; set; }
        public string TO_BUS_USR_NM { get; set; }
        public string FROM_ACCT_NBR { get; set; }
        public string TO_ACCT_NBR { get; set; }
        public string FROM_CRCY_CD { get; set; }
        public string TO_CRCY_CD { get; set; }
        public decimal CRCY_XCHG_RT { get; set; }
        public decimal FROM_TRANS_AMT { get; set; }
        public decimal TO_TRANS_AMT { get; set; }
        public string TRANS_SCD { get; set; }
        public System.DateTime TRANS_DT { get; set; }
        public string TRANS_TCD { get; set; }
        public string TRANS_DESC { get; set; }
    
        public virtual TBUS_USR TBUS_USR { get; set; }
        public virtual TBUS_USR TBUS_USR1 { get; set; }
    }
}
