//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS_CMSN
    {
        public int BUS_CMSN_ID { get; set; }
        public int FST_BUS_CMSN_ID { get; set; }
        public decimal FROM_AMT { get; set; }
        public decimal TO_AMT { get; set; }
        public int BN { get; set; }
        public string CTRY_CD { get; set; }
        public decimal FIX_CMSN_AMT { get; set; }
        public string CRCY_CD { get; set; }
        public decimal PRCNT_CMSN_RT { get; set; }
        public string BUS_CMSN_TCD { get; set; }
        public string BUS_CMSN_SCD { get; set; }
        public System.DateTime BUS_CMSN_DT { get; set; }
        public string BUS_OFR_SRVC_TO_OWN_CLT_IND { get; set; }
    
        public virtual TBUS TBUS { get; set; }
        public virtual TCTRY TCTRY { get; set; }
        public virtual TCRCY TCRCY { get; set; }
    }
}
