//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS_AGCY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBUS_AGCY()
        {
            this.TIP_ADDR = new HashSet<TIP_ADDR>();
            this.TBUS_USR_EXCP_ROL = new HashSet<TBUS_USR_EXCP_ROL>();
            this.TBUS_USR = new HashSet<TBUS_USR>();
            this.TBUS_AGCY_SRVC = new HashSet<TBUS_AGCY_SRVC>();
        }
    
        public int BN { get; set; }
        public string BUS_AGCY_NBR { get; set; }
        public string BUS_AGCY_NM { get; set; }
        public int BUS_AGCY_KTCT_ID { get; set; }
        public string BUS_AGCY_HDQRTR_IND { get; set; }
        public int BUS_AGCY_ACCT_ID { get; set; }
        public string BUS_AGCY_INTRNT_CHK_IND { get; set; }
        public decimal BUS_AGCY_MXAMT_TO_WDRW_AMT { get; set; }
        public decimal BUS_AGCY_AV_AMT { get; set; }
        public string BUS_AGCY_OPNNG_HR { get; set; }
        public string BUS_AGCY_NO_SRVC_AV_IND { get; set; }
    
        public virtual TACCT TACCT { get; set; }
        public virtual TBUS TBUS { get; set; }
        public virtual TKTCT TKTCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIP_ADDR> TIP_ADDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_USR_EXCP_ROL> TBUS_USR_EXCP_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_USR> TBUS_USR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_AGCY_SRVC> TBUS_AGCY_SRVC { get; set; }
    }
}
