//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS_AGCY_SRVC
    {
        public int BUS_AGCY_SRVC_ID { get; set; }
        public int BN { get; set; }
        public string BUS_AGCY_NBR { get; set; }
        public string BUS_AGCY_SRVC_CD { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        public virtual TBUS_AGCY TBUS_AGCY { get; set; }
    }
}
