//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUS_USR_EXCP_ROL
    {
        public int BUS_USR_EXCP_ROL_ID { get; set; }
        public int BUS_USR_NBR { get; set; }
        public int BN { get; set; }
        public string BUS_AGCY_NBR { get; set; }
        public string BUS_USR_EXCP_ROL_EXPY_IND { get; set; }
        public System.DateTime BUS_USR_EXCP_ROL_EDT { get; set; }
        public System.DateTime BUS_USR_EXCP_ROL_XDT { get; set; }
        public string TRANS_TRSF_CRDT_DBT_TCD { get; set; }
    
        public virtual TBUS_AGCY TBUS_AGCY { get; set; }
        public virtual TBUS_USR TBUS_USR { get; set; }
    }
}
