//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCAL_CTRY
    {
        public string CTRY_CD { get; set; }
        public string CAL_CTRY_CD { get; set; }
        public short CTRY_PHN_NBR_LNGH_CNT { get; set; }
        public System.DateTime CTRY_PHN_NBR_LNGH_LST_UPD_DT { get; set; }
        public string LGC_DEL_IND { get; set; }
    }
}
