//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCARD()
        {
            this.TBUS = new HashSet<TBUS>();
            this.TCLT_IN_BUS = new HashSet<TCLT_IN_BUS>();
        }
    
        public int CARD_ID { get; set; }
        public string CARD_OWNR_FNM { get; set; }
        public string CARD_NBR { get; set; }
        public string CARD_CVV_CD { get; set; }
        public string CARD_PIN { get; set; }
        public System.DateTime CARD_EDT { get; set; }
        public System.DateTime CARD_XDT { get; set; }
        public string CARD_TCD { get; set; }
        public string CARD_SCD { get; set; }
        public string CARD_CTRY_CD { get; set; }
        public System.DateTime CARD_CDT { get; set; }
        public string USR_NBR { get; set; }
        public string DFLT_PIN_IND { get; set; }
        public string PHYS_CARD_SCD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS> TBUS { get; set; }
        public virtual TCTRY TCTRY { get; set; }
        public virtual TUSR TUSR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCLT_IN_BUS> TCLT_IN_BUS { get; set; }
    }
}
