//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCNX_LOG
    {
        public string USR_NBR { get; set; }
        public int QUES1 { get; set; }
        public string RESP1 { get; set; }
        public int QUES2 { get; set; }
        public string RESP2 { get; set; }
        public int QUES3 { get; set; }
        public string RESP3 { get; set; }
        public int CNX_SCTY_QUES_SEQ_NBR { get; set; }
        public string CNX_SCTY_QUES_CHKED { get; set; }
        public string IP_ADDR_NBR { get; set; }
        public string IP_VERS_TCD { get; set; }
        public System.DateTime LAST_CNX_DTTM { get; set; }
    
        public virtual TUSR TUSR { get; set; }
        public virtual TSCTY_QUES_LIST TSCTY_QUES_LIST { get; set; }
        public virtual TSCTY_QUES_LIST TSCTY_QUES_LIST1 { get; set; }
        public virtual TSCTY_QUES_LIST TSCTY_QUES_LIST2 { get; set; }
    }
}
