//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXCEPT_TRANS
    {
        public int TRANS_ID { get; set; }
        public string EXCEPT_TRANS_RCD { get; set; }
        public string TRANS_AUTH_KTCT_CD { get; set; }
        public string TRANS_AUTH_KTCT_PHN { get; set; }
        public string ACTION_TAKEN_DESC { get; set; }
        public string USR_NBR { get; set; }
    
        public virtual TTRANS_TRSF_CRDT_DBT TTRANS_TRSF_CRDT_DBT { get; set; }
        public virtual TUSR TUSR { get; set; }
    }
}
