//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFI
    {
        public int FI_ID { get; set; }
        public string FI_FRA_NM { get; set; }
        public string FI_ENG_NM { get; set; }
        public string FI_SPA_NM { get; set; }
        public string FI_ARB_NM { get; set; }
        public string FI_POR_NM { get; set; }
        public string FI_ZHO_NM { get; set; }
        public string FI_RUS_NM { get; set; }
        public string FI_DEU_NM { get; set; }
        public string FI_ITA_NM { get; set; }
        public string LGC_DEL_IND { get; set; }
    }
}
