//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFI_EXRL_ACCT_DESC
    {
        public int EXRL_ACCT_DESC_ID { get; set; }
        public string EXRL_ACCT_PRT1_DESC { get; set; }
        public string EXRL_ACCT_PRT2_DESC { get; set; }
        public string EXRL_ACCT_PRT3_DESC { get; set; }
        public string EXRL_ACCT_PRT4_DESC { get; set; }
        public string EXRL_ACCT_PRT5_DESC { get; set; }
        public System.DateTime EXRL_ACCT_DESC_DT { get; set; }
        public string CTRY_CD { get; set; }
    
        public virtual TCTRY TCTRY { get; set; }
    }
}
