//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TID_DOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TID_DOC()
        {
            this.TTRANS_ID_DOC = new HashSet<TTRANS_ID_DOC>();
        }
    
        public int ID_DOC_ID { get; set; }
        public string FRA_ID_DOC_NM { get; set; }
        public string ENG_ID_DOC_NM { get; set; }
        public string SPA_ID_DOC_NM { get; set; }
        public string ARB_ID_DOC_NM { get; set; }
        public string POR_ID_DOC_NM { get; set; }
        public string ZHO_ID_DOC_NM { get; set; }
        public string RUS_ID_DOC_NM { get; set; }
        public string DEU_ID_DOC_NM { get; set; }
        public string ITA_ID_DOC_NM { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_ID_DOC> TTRANS_ID_DOC { get; set; }
    }
}
