//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIP_ADDR
    {
        public string IP_ADDR_NBR { get; set; }
        public string IP_VERS_TCD { get; set; }
        public string IP_ADDR_DESC { get; set; }
        public Nullable<int> BN { get; set; }
        public string BUS_AGCY_NBR { get; set; }
        public System.DateTime IP_ADDR_CRT_DT { get; set; }
        public string IP_ADDR_CRT_UPD_USR_NBR { get; set; }
    
        public virtual TBUS_AGCY TBUS_AGCY { get; set; }
        public virtual TUSR TUSR { get; set; }
    }
}
