//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKTCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TKTCT()
        {
            this.TBUS = new HashSet<TBUS>();
            this.TBUS_AGCY = new HashSet<TBUS_AGCY>();
            this.TUSR = new HashSet<TUSR>();
        }
    
        public int KTCT_ID { get; set; }
        public string ADDR_LN1_TXT { get; set; }
        public string ADDR_LN2_TXT { get; set; }
        public string PHN1_NBR { get; set; }
        public string PHN2_NBR { get; set; }
        public string EM_ADDR1_TXT { get; set; }
        public string EM_ADDR2_TXT { get; set; }
        public string WEBSITE_TXT { get; set; }
        public string KTCT_TCD { get; set; }
        public string CITY_NM { get; set; }
        public string CTRY_CD { get; set; }
        public Nullable<int> CITY_CD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS> TBUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBUS_AGCY> TBUS_AGCY { get; set; }
        public virtual TCITY TCITY { get; set; }
        public virtual TCTRY TCTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUSR> TUSR { get; set; }
    }
}
