//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMNYT_AUTH_LMIT
    {
        public string CTRY_CD { get; set; }
        public string CRCY_CD { get; set; }
        public string MNYT_TCD { get; set; }
        public decimal TRANS_AUTH_AMT { get; set; }
        public decimal DLY_AUTH_AMT { get; set; }
        public decimal WKLY_AUTH_AMT { get; set; }
        public decimal MTHLY_AUTH_AMT { get; set; }
        public System.DateTime LAST_UPDT_DT { get; set; }
    
        public virtual TCRCY TCRCY { get; set; }
        public virtual TCTRY TCTRY { get; set; }
    }
}
