//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPKP_TRCK_CMSN_FEE
    {
        public long PKP_TRCK_CMSN_FEE_ID { get; set; }
        public string TRANS_ID { get; set; }
        public decimal TRANS_AMT { get; set; }
        public string TRANS_CRCY_CD { get; set; }
        public decimal TRANS_US_AMT { get; set; }
        public string BUS_AGNT_NBR { get; set; }
        public string BUS_AGNT_TCD { get; set; }
        public System.DateTime TRANS_DT { get; set; }
        public string SRVC_TCD { get; set; }
        public string CMSN_FEE_TCD { get; set; }
    }
}
