//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPROV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPROV()
        {
            this.TTRANS_FEE = new HashSet<TTRANS_FEE>();
            this.TTRSF_SERV_CTRY = new HashSet<TTRSF_SERV_CTRY>();
        }
    
        public int PROV_CD { get; set; }
        public string FRA_PROV_NM { get; set; }
        public string ENG_PROV_NM { get; set; }
        public string SPA_PROV_NM { get; set; }
        public string ARB_PROV_NM { get; set; }
        public string POR_PROV_NM { get; set; }
        public string ZHO_PROV_NM { get; set; }
        public string RUS_PROV_NM { get; set; }
        public string DEU_PROV_NM { get; set; }
        public string ITA_PROV_NM { get; set; }
        public string CTRY_CD { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        public virtual TCTRY TCTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRANS_FEE> TTRANS_FEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRSF_SERV_CTRY> TTRSF_SERV_CTRY { get; set; }
    }
}
