//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPYMT_PRTR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPYMT_PRTR()
        {
            this.TEXRL_TRANS = new HashSet<TEXRL_TRANS>();
        }
    
        public string PYMT_PRTR_ID { get; set; }
        public string PYMT_PRTR_NM { get; set; }
        public System.DateTime PYMT_PRTR_EDT { get; set; }
        public System.DateTime PYMT_PRTR_XDT { get; set; }
        public string PYMT_PRTR_DESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEXRL_TRANS> TEXRL_TRANS { get; set; }
    }
}
