//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRCPT_EXRL_ACCT_FOR_BUS
    {
        public int RCPT_EXRL_ACCT_FOR_BUS_ID { get; set; }
        public Nullable<int> EXRL_ACCT_ID { get; set; }
        public Nullable<int> RCPT_USR_BUS_ID { get; set; }
        public int BN { get; set; }
        public string RCPT_EXRL_ACCT_FOR_BUS_TCD { get; set; }
    
        public virtual TBUS TBUS { get; set; }
        public virtual TFI_EXRL_ACCT TFI_EXRL_ACCT { get; set; }
        public virtual TRCPT_USR_BUS TRCPT_USR_BUS { get; set; }
    }
}
