//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSCTY_QUES_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSCTY_QUES_LIST()
        {
            this.TCNX_LOG = new HashSet<TCNX_LOG>();
            this.TCNX_LOG1 = new HashSet<TCNX_LOG>();
            this.TCNX_LOG2 = new HashSet<TCNX_LOG>();
        }
    
        public int SCTY_QUES_ID { get; set; }
        public string SCTY_QUES_FRA { get; set; }
        public string SCTY_QUES_ENG { get; set; }
        public string SCTY_QUES_SPA { get; set; }
        public string SCTY_QUES_ARB { get; set; }
        public string SCTY_QUES_POR { get; set; }
        public string SCTY_QUES_ZHO { get; set; }
        public string SCTY_QUES_RUS { get; set; }
        public string SCTY_QUES_DEU { get; set; }
        public string SCTY_QUES_ITA { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCNX_LOG> TCNX_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCNX_LOG> TCNX_LOG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCNX_LOG> TCNX_LOG2 { get; set; }
    }
}
