//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTRANS_FEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTRANS_FEE()
        {
            this.TTRSF_FEE_SERV_CTRY = new HashSet<TTRSF_FEE_SERV_CTRY>();
        }
    
        public int TRANS_FEE_ID { get; set; }
        public Nullable<int> PROV_CD { get; set; }
        public string FROM_CRCY_CD { get; set; }
        public string TO_CRCY_CD { get; set; }
        public decimal FROM_AMT { get; set; }
        public decimal TO_AMT { get; set; }
        public decimal IVSTR_FIX_FEE_AMT { get; set; }
        public decimal IVSTR_PRCNT_FEE_RT { get; set; }
        public decimal NIVSTR_FIX_FEE_AMT { get; set; }
        public decimal NIVSTR_PRCNT_FEE_RT { get; set; }
        public int CRCY_XCHG_PRCNT_ID { get; set; }
        public string TRANS_FEE_TCD { get; set; }
        public System.DateTime TRANS_FEE_DT { get; set; }
        public string TRANS_FEE_GRP_NM { get; set; }
        public int TRANS_FEE_GRP_ID { get; set; }
        public string TRANS_FEE_GRP_IND { get; set; }
    
        public virtual TCRCY TCRCY { get; set; }
        public virtual TCRCY TCRCY1 { get; set; }
        public virtual TCRCY_XCHG_PRCNT TCRCY_XCHG_PRCNT { get; set; }
        public virtual TPROV TPROV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRSF_FEE_SERV_CTRY> TTRSF_FEE_SERV_CTRY { get; set; }
    }
}
