//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTRSF_SERV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTRSF_SERV()
        {
            this.TTRSF_FEE_SERV_CTRY = new HashSet<TTRSF_FEE_SERV_CTRY>();
            this.TTRSF_FEE_SERV_CTRY1 = new HashSet<TTRSF_FEE_SERV_CTRY>();
            this.TTRSF_SERV_CTRY = new HashSet<TTRSF_SERV_CTRY>();
        }
    
        public int TRSF_SERV_ID { get; set; }
        public string FRA_TRSF_SERV_NM { get; set; }
        public string ENG_TRSF_SERV_NM { get; set; }
        public string SPA_TRSF_SERV_NM { get; set; }
        public string ARB_TRSF_SERV_NM { get; set; }
        public string POR_TRSF_SERV_NM { get; set; }
        public string ZHO_TRSF_SERV_NM { get; set; }
        public string RUS_TRSF_SERV_NM { get; set; }
        public string DEU_TRSF_SERV_NM { get; set; }
        public string ITA_TRSF_SERV_NM { get; set; }
        public string LGC_DEL_IND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRSF_FEE_SERV_CTRY> TTRSF_FEE_SERV_CTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRSF_FEE_SERV_CTRY> TTRSF_FEE_SERV_CTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTRSF_SERV_CTRY> TTRSF_SERV_CTRY { get; set; }
    }
}
