//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTRSF_SERV_CTRY
    {
        public int TRSF_SERV_CTRY_ID { get; set; }
        public string CTRY_CD { get; set; }
        public int PROV_CD { get; set; }
        public int TRSF_SERV_ID { get; set; }
        public string TRSF_TCD { get; set; }
        public System.DateTime LAST_UPDT_DT { get; set; }
    
        public virtual TCTRY TCTRY { get; set; }
        public virtual TPROV TPROV { get; set; }
        public virtual TTRSF_SERV TTRSF_SERV { get; set; }
    }
}
