//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaykapDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTMNYT_FEE_EXPIRED
    {
        public int MNYT_FEE_ID { get; set; }
        public string MNYT_FEE_GRP_CD { get; set; }
        public decimal FROM_AMT { get; set; }
        public decimal TO_AMT { get; set; }
        public decimal FIX_FEE_AMT { get; set; }
        public decimal PRCNT_FEE { get; set; }
        public decimal PRCNT_NO_99P_FRC_INV { get; set; }
        public string FROM_CRCY_CD { get; set; }
        public string MNYT_FEE_TCD { get; set; }
        public System.DateTime LAST_UPDT_DT { get; set; }
    
        public virtual TCRCY TCRCY { get; set; }
    }
}
